### ISSUE TITLE
Cannot read property 'negated' of undefined

### ISSUE THREAD

**Issue by testarossaaaaa** [caub/pg-tsquery#6]
Error raised with this input `Some query (*`, we always adds * for our autocomplete system.

**Comment by caub** [comment]
Nice catch, for now `Some query (:*` can work

But I'll really rework this library, and make everything configurable, so you can define if spacing behaves as a AND or as a FOLLOWED_BY (so the above query would be `'some' <-> 'query':*` instead of `'some' & 'query':*`, note that `(` is stripped, I need to think of a way to escape it), and which tokens are used for AND, OR, FOLLOWED_BY, etc..

Can you tell me how you're using this library? are you doing `"to_tsvector(some_column) @@ to_tsquery($1)", tsquery(inputStr)` ? Why not using `LIKE`/`ILIKE` if you plan to only match exact content?

**Comment by testarossaaaaa** [comment]
This library is used by https://github.com/mlipscombe/postgraphile-plugin-fulltext-filter which in turn is used by https://github.com/graphile/postgraphile.

We use FTS and useful FTS functions and triggers, so exact match with `like` is not our cup of tea.

**Comment by testarossaaaaa** [comment]
Also we do not use any modificators, just a sanitizing and a simply raw input with `:*` at the end.

**Comment by caub** [comment]
I fixed the raised error, but `foo bar (*` is going to be parsed as `foo&bar` (or some other operator, `foo<->bar` possibly), there's nothing much to do with the `(*` at the end, because parentheses can't reasonably be escaped (see https://stackoverflow.com/a/18130246/3183756), and they have a meaning, plus the prefix operator at the end needs to be after a word, and there's none before

**Comment by testarossaaaaa** [comment]
I think this is what we need, thank you!
